### PR TITLE
fix border-radius

### LINKED ISSUE #253: Unify border radius
Some input elements don't have the same border radius, e.g in the send modal.
Note that this is one instance of such an inconsistency, please take a look around to find these and fix them all in the same PR.

image

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #253

### CODE REVIEW

File: packages/ui/src/components/Transactions/Transaction.tsx [hunk 1]
```diff
@@ -141,7 +141,7 @@ export default styled(Transaction)(
     max-height: 1.3125rem;
     left: 29px;
     top: 19px;
-    border-radius: 0 0.9375rem 0.9375rem 0.9375rem;
+    border-radius: ${theme.custom.borderRadius};
```
Comment (Tbaut) [inline packages/ui/src/components/Transactions/Transaction.tsx:144]: This breaks the effect of having the top left not having any in the top left. Not sure if this suggestion works, we we could try

```suggestion
    border-radius: 0  ${theme.custom.borderRadius}  ${theme.custom.borderRadius} ${theme.custom.borderRadius};
```

**Review by Tbaut — COMMENTED** [review]
Thanks, it def looks more consistent that way.
There's just a little thing that I made a suggestion for. If that work I think it's better, if not we can forget as this will be changed eventually.

File: packages/ui/src/components/Transactions/Transaction.tsx (hunk 1 above)
Comment (Lykhoyda) [reply packages/ui/src/components/Transactions/Transaction.tsx:144]: I think the new design doesn't have that view for the badge. So I think we can consider it as a deprecated and keep the new design

Comment (Tbaut) [reply packages/ui/src/components/Transactions/Transaction.tsx:144]: this is not implementing the new design though, we're in the old, changing border-radius. Now if that's something you've strong opinion about, because you don't like it, I can let it go.

**Review by Tbaut — APPROVED** [review]

**Comment by Tbaut** [comment]
I guess it's ready to merge?

**Comment by Lykhoyda** [comment]
> I guess it's ready to merge?

Now we can merge, got the reply from Cindy about unified border-radius
